services:
    db:
        image: mysql:9.0
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: ${DB_NAME}
            MYSQL_USER: ${DB_USER}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            TZ: "Asia/Tokyo"
        volumes:
            - db-data:/var/lib/mysql
            - ./mysql/conf.d:/etc/mysql/conf.d

volumes:
    db-data:
